# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Git Config
      run: |
        git config --global user.email charmingYouYou@github.com
        git config --global user.name charmingYouYou
        git remote add origin https://${{secrets.ACCESS_TOKEN}}@github.com/charmingYouYou/youyou_excel.git
    - name: 安装依赖
      run: yarn
    - name: 编译构建
      run: sh deploy.sh
